name: DynaBench
channels:
  - conda-forge
  - defaults
dependencies:
  - ipywidgets
  - pip
  - ipykernel
  - pdbfixer
  - jupyter
  - python >= 3.9
  - seaborn
  - mdanalysis
  - python-kaleido
  - jsonpickle
  - moviepy
  - matplotlib
  - pip:
     - pdb-tools
     - freesasa
     - nglview
